name: CI-CD to Minikube

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        shell: pwsh

      - name: Enable debug logs
        shell: pwsh
        run: |
          $env:GITHUB_ACTIONS = "true"
          $env:ACTIONS_RUNNER_DEBUG = "true"
          $env:ACTIONS_STEP_DEBUG = "true"

      - name: Docker login
        shell: pwsh
        run: |
          Write-Output "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        shell: pwsh
        run: |
          docker build -t esakkimuthus/springapp1:${{ github.sha }} .

      - name: Push Docker image
        shell: pwsh
        run: |
          docker push esakkimuthus/springapp1:${{ github.sha }}

      - name: Set KUBECONFIG
        shell: pwsh
        run: |
          $env:KUBECONFIG = "$($PWD.Path)\kubeconfig"
          Write-Host "KUBECONFIG path: $env:KUBECONFIG"

      - name: Check k8s folder
        shell: pwsh
        run: |
          if (!(Test-Path "k8s")) { throw "k8s folder not found" }

      - name: Deploy to Minikube
        shell: pwsh
        run: |
          kubectl apply -f k8s/
          kubectl set image deployment/spring-app spring-app=esakkimuthus/springapp1:${{ github.sha }}
          kubectl rollout status deployment/spring-app
