name: CI-CD to Minikube

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: |
        docker build -t esakkimuthus/springapp1:${{ github.sha }} .

    - name: Push Docker image
      run: |
        docker push esakkimuthus/springapp1:${{ github.sha }}

    # Remove Azure kubectl action
    #- name: Setup kubectl
    #  uses: azure/setup-kubectl@v4

    - name: Set KUBECONFIG environment
      shell: powershell
      run: |
        $env:KUBECONFIG = "$PWD\kubeconfig"

    - name: Deploy to Minikube
      shell: powershell
      run: |
        kubectl apply -f k8s/
        kubectl set image deployment/spring-app spring-app=esakkimuthus/springapp1:${{ github.sha }}
        kubectl rollout status deployment spring-app
